name: Sync to Vercel Fork

on:
  push:
    branches:
      - main

jobs:
  push-to-vercel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout org repo
        uses: actions/checkout@v3

      - name: Remove workflows before pushing
        run: |
          rm -rf .github/workflows

      - name: Clear credential cache
        run: |
          git config --global --unset credential.helper || true

      - name: Push to personal fork
        env:
          TOKEN: ${{ secrets.PRAJWAL_PERSONAL_TOKEN }}
        rrun: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git remote add vercel-fork https://x-access-token:${TOKEN}@github.com/prajwal-naik/nerd-nest-frontend.git
          git push vercel-fork main --force
