name: Sync Fork

on:
  push:
    branches:
      - main  # Change this if your default branch has a different name

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync fork
        uses: TG908/fork-sync@v2.3
        with:
          github_token: ${{ secrets.PAT }}
          owner: prajwal-naik
          base: main
          head: main
          repo: nerd-nest-frontend
          merge_branch: true