name: Sync Fork

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync fork
        uses: tgymnich/fork-sync@v1.6.0
        with:
          personal_token: ${{ secrets.PAT }}
          source_repository: nerdnest-bda/frontend
          target_repository: prajwal-naik/nerd-nest-frontend
          source_branch: main
          target_branch: main