name: Sync Fork

on:
  push:
    branches:
      - main  # Change this if your default branch has a different name

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to personal fork
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git remote add personal-fork https://$PAT@github.com/prajwal-naik/nerd-nest-frontend.git
          git push personal-fork main:main --force